<a href="https://colab.research.google.com/github/perfectpanda-works/machine-learning/blob/master/PyTorchTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PyTorch Tutorial

PyTorchの基本的な機能のTensorを利用する

In [ ]:
from __future__ import print_function
import torch

初期化なしでテンソルを作成するemptyメソッド。

2階テンソル（行列）の作成。5行3列

In [ ]:
x = torch.empty(5, 3)
print(x)

tensor([[3.9094e-36, 0.0000e+00, 5.0447e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3788e-14, 1.8369e+28, 1.9433e-19],
        [3.3738e-12, 7.4086e+28, 6.9397e+22],
        [1.7260e+25, 2.2856e+20, 5.0948e-14]])


ランダムに初期化した値を入れたテンソルの作成。randメソッド。

In [ ]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3082, 0.5270, 0.3674],
        [0.4574, 0.6412, 0.5187],
        [0.0847, 0.1587, 0.5561],
        [0.0908, 0.5013, 0.0632],
        [0.5202, 0.0063, 0.1726]])


0で初期化したテンソルを作成するzerosメソッド。
dtypeに0の型を指定できる。

In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


自分で初期値を指定してテンソルを作成するtensorメソッド。
1階のテンソル（ベクトル）を作成。

In [ ]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


２階のテンソル（行列）を作成。
行の間にカンマを忘れがち・・・

In [ ]:
x = torch.tensor([[5.5, 3],
                  [6.5, 4]])
print(x)

tensor([[5.5000, 3.0000],
        [6.5000, 4.0000]])


すでに作成したテンソルを再度定義し直す事もできます。
その時、指定していないパラメータは以前のものを引き継ぎます。
new_onesは1で埋めるメソッド。
xを5×3の行列と定義して、1で埋めます。そして、それぞれのデータはdouble型(float64型)とx自身のメソッドで定義し直すことができます。

In [ ]:
x = x.new_ones(5, 3, dtype=torch.double) 
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


テンソルをランダムな値で埋めて、データの型をfloat型に変更します。
テンソルのサイズは指定されていないので、xの5×3がそのまま引き継がれます。

In [ ]:
x = torch.randn_like(x, dtype=torch.float)
print(x)  

tensor([[ 0.2749, -0.7095, -1.1419],
        [ 0.7068,  0.0535, -1.1837],
        [ 0.4491, -0.9849, -1.7568],
        [ 0.3122,  0.1760,  0.8036],
        [ 1.1279,  1.2446, -1.9494]])


numpyでいう「.shape」は、sizeメソッドになります。

In [ ]:
print(x.size())

torch.Size([5, 3])


#テンソルの計算
慣れないベクトル（テンソル）の計算・・・

##足し算と引き算
###スカラー ＋ ベクトル

In [ ]:
x = 1
y = torch.tensor([4,5])

print(x)
print(y)

1
tensor([4, 5])


それぞれの要素にスカラーが足し合わされる。

In [ ]:
print(x + y)

tensor([5, 6])


同じように、addメソッドでも足すことができます。

In [ ]:
print(torch.add(x, y))

tensor([5, 6])


「torch.add」では次のように出力を指定してテンソル同士を足し合わせる事もできます。

In [ ]:
result = torch.empty(1,2)
torch.add(x, y, out=result)
print(result)

tensor([5., 6.])


同様に引き算です。

In [ ]:
print(x - y)

tensor([-3, -4])


###ベクトル+ベクトル
ベクトル同士の足し算、引き算は、同じサイズ同士である必要がある。

In [ ]:
x2 = torch.tensor([1,2,3])
y2 = torch.tensor([4,5,6])

print(x2)
print(y2)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [ ]:
print(x2 + y2)

tensor([5, 7, 9])


In [ ]:
print(x2 - y2)

tensor([-3, -3, -3])


サイズが違う場合エラー

In [ ]:
x2 = torch.tensor([1,2])
y2 = torch.tensor([4,5,6])

print(x2)
print(y2)

tensor([1, 2])
tensor([4, 5, 6])


In [ ]:
print(x2 + y2)

RuntimeError: ignored

###行列の足し算引き算


スカラー、行列

In [ ]:
x3 = 1
y3 = torch.tensor([[1,2,3],
                    [4,5,6]])

print(x3)
print(y3)

1
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
print(x3 + y3)

tensor([[2, 3, 4],
        [5, 6, 7]])


ベクトル、行列
行、または列が同じ

In [ ]:
x4 = torch.tensor([1,2,3])
y4 = torch.tensor([[1,2,3],
                    [4,5,6]])

print(x4 + y4)

tensor([[2, 4, 6],
        [5, 7, 9]])


In [ ]:
x5 = torch.tensor([[1],
                    [2]])
y5 = torch.tensor([[1,2,3],
                    [4,5,6]])

print(x5 + y5)

tensor([[2, 3, 4],
        [6, 7, 8]])


###行列と行列

In [ ]:
x6 = torch.tensor([[1,2,3],
                    [3,2,1]])
y6 = torch.tensor([[1,2,3],
                    [3,2,1]])

print(x6 + y6)

tensor([[2, 4, 6],
        [6, 4, 2]])


上書きして足し合わせる場合、次のような表記方法も可能です。

add_メソッド

In [ ]:
y6.add_(x6)
print(y6)

tensor([[2, 4, 6],
        [6, 4, 2]])


y6に、x6とy6を足した結果が代入されました。

numpyのスライス表記のようにテンソルの要素を取り出すことができます。

In [ ]:
print(y6[:,0])

tensor([2, 6])


y6から、1列目の全ての行を取り出しました。

##テンソルのサイズ変更

In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


zに指定した-1は、他の要素から推定されるという意味です。例えば、列が8になると、もともとxには16個のデータ（4×4）しかないので、２行になるので、　-1は自動的に2を入れることになります。

次のように、要素数に矛盾が生じる場合、エラーになります。

In [ ]:
y = x.view(15)

RuntimeError: ignored

1要素のみのテンソルをitemメソッドでPythonの数値として取り出すことができるそうです。

In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.9216])
-0.9215939044952393


使い所が不明だったので、少し調べたところ、平均を取り出す時に使いそうです。
ちなみに、meanを利用することで、テンソルの平均値が取り出せるそうです。

In [ ]:
x = torch.tensor([5.0, 4.0, 3.0])
average = x.mean()
print(average)

print(average.item())

tensor(4.)
4.0


他にも、たくさんの構文があるので、こちらで確認してね、というチュートリアルになっています・・・

#NumPy←→PyTorch
###PyTorchのtensor型をnumpy配列に変換

In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


tensorからnumpyに変換したものは、連動しているみたいです。

In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


###Numpy配列をPyTorchのtensor型に変換

In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CUDAというNVIDIAのGPU並列処理する仕組みを利用して、CUDAで処理できるようなメソッドが「.to」とのことです。CUDA環境ではないので、実行できませんでしたが、簡単にGPUでテンソルを処理するのか、CPUで処理するのかが記載できます。

In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!