<a href="https://colab.research.google.com/github/perfectpanda-works/machine-learning/blob/master/PyTorchTutorial_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#自動微分
PyTorchのautogradパッケージを利用するチュートリアル

In [ ]:
import torch

requires_grad=Trueとしてtensorを作成することで、計算を追跡するようになります。計算を追跡とは、計算を記録していくということになります。

In [ ]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


PyTorchでは、tensorが基本になるので、普通の数値計算の場合もスカラーとしてtensorで作成します。

In [ ]:
x_scalar = torch.tensor(3.0 , requires_grad=True)
print(x_scalar)

tensor(3., requires_grad=True)


チュートリアルでは次に、テンソルxを元に演算を行っていきます。

In [ ]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


計算はgrad_fnに記録されていくようです。

In [ ]:
print(y.grad_fn)

さらにyから計算を進めています。zという新しい変数と、outという新しい変数が出てきます。

In [ ]:
z = y * y * 3
out = z.mean()

print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


zのgrad_fn、outのgrad_fnにそれぞれ計算が記録されていきました。


自分でtensorを作成するときに、「requires_grad=True」を指定しておかないと、計算が記録されていないことになります。

プログラムの途中でrequired_gradをtrueにするには、「a.required_grad_(True)」のようにメソッドで指定することで変更できます。

In [ ]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


#勾配を求める
計算グラフでいう、出力「out」からバックワード微分を行うのが「.backword()」

In [ ]:
out.backward()

計算の勾配が求められたので、次のようにして、確認したい勾配を出力できます。
xのoutに対する勾配「∂out/∂x」は「x.grad」のように確認できます。

In [ ]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


このようにして、outに対するxの勾配を素早く計算することができます。バックプロパゲーションでは、このように求めた勾配に学習係数をかけたもので重みを変化させて、勾配が最小の値となるような重みを探します。