<a href="https://colab.research.google.com/github/perfectpanda-works/machine-learning/blob/master/SKL_iris_data_splitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#scikit-learnでアヤメデータを読み込む

In [0]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

panda_box = load_iris()

##読み込んだデータの確認

In [0]:
X = panda_box.data
y = panda_box.target
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

#訓練データとテストデータの分割

##train_test_split関数

In [0]:
#学習データとテスト用データへ分割(半分の75づつ)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5)

##データ形状の確認

In [0]:
#データ個数の確認
print("X_train", X_train.shape)
print("X_test", X_test.shape)
print("y_train", y_train.shape)
print("y_test", y_test.shape)

X_train (75, 4)
X_test (75, 4)
y_train (75,)
y_test (75,)


訓練データとテストデータにどのアヤメの種類がどれだけ含まれているか確認

In [0]:
#データのばらつき具合の確認
print("訓練データのデータ割合")
print(np.unique(y_train, return_counts=True))
data, kosuu = np.unique(y_train, return_counts=True)
print('{:.2f}'.format(kosuu[0]/kosuu.sum()),
      '{:.2f}'.format(kosuu[1]/kosuu.sum()),
      '{:.2f}'.format(kosuu[2]/kosuu.sum()))

print("テストデータのデータ割合")
print(np.unique(y_test, return_counts=True))
data2, kosuu2 = np.unique(y_test, return_counts=True)
print('{:.2f}'.format(kosuu2[0]/kosuu2.sum()), 
      '{:.2f}'.format(kosuu2[1]/kosuu2.sum()),
      '{:.2f}'.format(kosuu2[2]/kosuu2.sum()))

訓練データのデータ割合
(array([0, 1, 2]), array([23, 22, 30]))
0.31 0.29 0.40
テストデータのデータ割合
(array([0, 1, 2]), array([27, 28, 20]))
0.36 0.37 0.27


##stratify

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, stratify=y)

In [0]:
print("X_train", X_train.shape)
print("X_test", X_test.shape)
print("y_train", y_train.shape)
print("y_test", y_test.shape)

X_train (75, 4)
X_test (75, 4)
y_train (75,)
y_test (75,)


In [0]:
print("stratify後の訓練データのデータ割合")
print(np.unique(y_train, return_counts=True))
data, kosuu = np.unique(y_train, return_counts=True)
print('{:.2f}'.format(kosuu[0]/kosuu.sum()),
      '{:.2f}'.format(kosuu[1]/kosuu.sum()),
      '{:.2f}'.format(kosuu[2]/kosuu.sum()))

print("stratify後のテストデータのデータ割合")
print(np.unique(y_test, return_counts=True))
data2, kosuu2 = np.unique(y_test, return_counts=True)
print('{:.2f}'.format(kosuu2[0]/kosuu2.sum()),
      '{:.2f}'.format(kosuu2[1]/kosuu2.sum()),
      '{:.2f}'.format(kosuu2[2]/kosuu2.sum()))

stratify後の訓練データのデータ割合
(array([0, 1, 2]), array([25, 25, 25]))
0.33 0.33 0.33
stratify後のテストデータのデータ割合
(array([0, 1, 2]), array([25, 25, 25]))
0.33 0.33 0.33
