<a href="https://colab.research.google.com/github/perfectpanda-works/machine-learning/blob/master/stack%E3%81%AEdim%E3%81%AE%E6%8C%87%E5%AE%9A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

#2×3の行列をテンソルとして準備
x = torch.randn(2, 3)
x

tensor([[ 0.7329, -1.1706, -0.3256],
        [-0.3038,  1.0603,  1.0140]])

In [ ]:
#リストを作成します。
x_list = []
x_list.append(x)
x_list.append(x)
x_list.append(x)

全てのテンソルが同じサイズである必要があります。
今回はすべて同じテンソルの複製なのでOK

デフォルトでdim=0の設定。

In [ ]:
print(torch.stack(x_list))
torch.stack(x_list).size()

tensor([[[ 0.7329, -1.1706, -0.3256],
         [-0.3038,  1.0603,  1.0140]],

        [[ 0.7329, -1.1706, -0.3256],
         [-0.3038,  1.0603,  1.0140]],

        [[ 0.7329, -1.1706, -0.3256],
         [-0.3038,  1.0603,  1.0140]]])


torch.Size([3, 2, 3])

In [ ]:
print(torch.stack(x_list, dim=1))
torch.stack(x_list, dim=1).size()

tensor([[[ 0.7329, -1.1706, -0.3256],
         [ 0.7329, -1.1706, -0.3256],
         [ 0.7329, -1.1706, -0.3256]],

        [[-0.3038,  1.0603,  1.0140],
         [-0.3038,  1.0603,  1.0140],
         [-0.3038,  1.0603,  1.0140]]])


torch.Size([2, 3, 3])

In [ ]:
print(torch.stack(x_list, dim=2))
torch.stack(x_list, dim=2).size()

tensor([[[ 0.7329,  0.7329,  0.7329],
         [-1.1706, -1.1706, -1.1706],
         [-0.3256, -0.3256, -0.3256]],

        [[-0.3038, -0.3038, -0.3038],
         [ 1.0603,  1.0603,  1.0603],
         [ 1.0140,  1.0140,  1.0140]]])


torch.Size([2, 3, 3])

RGB画像の３チャンネルデータを想定した場合

一般的なカラー画像では、赤(R)のみを0～255で表現する画像、緑(G)のみを0～255で表現する画像、青(B)のみを0～255で表現する画像の３枚（３チャンネル）の画像をひとつにしてカラー画像を表現しています。(透明情報のアルファが加わって4チャンネルとなる場合もあります。）

PyTorchのテンソルでこのカラー画像１枚を表現すると、次のようなテンソルのサイズになります。

In [ ]:
rgb = torch.randn(3, 2, 3)
rgb

tensor([[[ 1.0691,  0.0893, -0.9815],
         [-0.6828, -1.6071,  0.4074]],

        [[ 1.1217,  1.9044,  0.1318],
         [ 0.0065,  1.7577, -0.4926]],

        [[ 0.2009,  0.2247, -0.6303],
         [-1.0737,  0.1366, -1.2880]]])

In [ ]:
#リストを作成します。
rgb_list = []
rgb_list.append(rgb)
rgb_list.append(rgb)
rgb_list.append(rgb)
rgb_list.append(rgb)

In [ ]:
print(torch.stack(rgb_list))
torch.stack(rgb_list).size()

tensor([[[[ 1.0691,  0.0893, -0.9815],
          [-0.6828, -1.6071,  0.4074]],

         [[ 1.1217,  1.9044,  0.1318],
          [ 0.0065,  1.7577, -0.4926]],

         [[ 0.2009,  0.2247, -0.6303],
          [-1.0737,  0.1366, -1.2880]]],


        [[[ 1.0691,  0.0893, -0.9815],
          [-0.6828, -1.6071,  0.4074]],

         [[ 1.1217,  1.9044,  0.1318],
          [ 0.0065,  1.7577, -0.4926]],

         [[ 0.2009,  0.2247, -0.6303],
          [-1.0737,  0.1366, -1.2880]]],


        [[[ 1.0691,  0.0893, -0.9815],
          [-0.6828, -1.6071,  0.4074]],

         [[ 1.1217,  1.9044,  0.1318],
          [ 0.0065,  1.7577, -0.4926]],

         [[ 0.2009,  0.2247, -0.6303],
          [-1.0737,  0.1366, -1.2880]]],


        [[[ 1.0691,  0.0893, -0.9815],
          [-0.6828, -1.6071,  0.4074]],

         [[ 1.1217,  1.9044,  0.1318],
          [ 0.0065,  1.7577, -0.4926]],

         [[ 0.2009,  0.2247, -0.6303],
          [-1.0737,  0.1366, -1.2880]]]])


torch.Size([4, 3, 2, 3])